"""empty message

Revision ID: 10f5c6fec536
Revises: 3c458ab7ad8c
Create Date: 2016-01-21 10:45:53.244733

"""

# revision identifiers, used by Alembic.
revision = '10f5c6fec536'
down_revision = '3c458ab7ad8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('module_letter', sa.String(length=20), nullable=False),
    sa.Column('dev_interface', sa.String(length=200), nullable=False),
    sa.Column('op_interface', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    ### end Alembic commands ###
