"""empty message

Revision ID: 155783ce6964
Revises: 10f5c6fec536
Create Date: 2016-01-21 11:30:02.730663

"""

# revision identifiers, used by Alembic.
revision = '155783ce6964'
down_revision = '10f5c6fec536'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('switch')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switch',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('switch_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('switch_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('manager_ip', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('idc_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cabinet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('expire', mysql.DATETIME(), nullable=True),
    sa.Column('remark', mysql.TEXT(), nullable=True),
    sa.Column('manufacturers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_op_time', mysql.DATETIME(), nullable=True),
    sa.Column('last_op_people', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('switch_port_nums', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
