"""empty message

Revision ID: 2294cb4ebe5f
Revises: 155783ce6964
Create Date: 2016-01-21 11:31:18.405413

"""

# revision identifiers, used by Alembic.
revision = '2294cb4ebe5f'
down_revision = '155783ce6964'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(length=50), nullable=False),
    sa.Column('switch_type', sa.String(length=50), nullable=False),
    sa.Column('manager_ip', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('idc_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('manufacturers', sa.Integer(), nullable=False),
    sa.Column('last_op_time', sa.DateTime(), nullable=True),
    sa.Column('last_op_people', sa.Integer(), nullable=False),
    sa.Column('switch_port_nums', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_switch_cabinet_id'), 'switch', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_switch_idc_id'), 'switch', ['idc_id'], unique=False)
    op.create_index(op.f('ix_switch_manufacturers'), 'switch', ['manufacturers'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_switch_manufacturers'), table_name='switch')
    op.drop_index(op.f('ix_switch_idc_id'), table_name='switch')
    op.drop_index(op.f('ix_switch_cabinet_id'), table_name='switch')
    op.drop_table('switch')
    ### end Alembic commands ###
