"""empty message

Revision ID: 34b85bb91295
Revises: 7de1ffb7774f
Create Date: 2016-01-21 14:16:24.689826

"""

# revision identifiers, used by Alembic.
revision = '34b85bb91295'
down_revision = '7de1ffb7774f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipinfo', sa.Column('switch_port', sa.Integer(), nullable=True))
    op.drop_column('ipinfo', 'swithc_port')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipinfo', sa.Column('swithc_port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('ipinfo', 'switch_port')
    ### end Alembic commands ###
