"""empty message

Revision ID: 3c458ab7ad8c
Revises: 0f18cf4ae43a
Create Date: 2016-01-21 10:38:01.508965

"""

# revision identifiers, used by Alembic.
revision = '3c458ab7ad8c'
down_revision = '0f18cf4ae43a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('service_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('module_letter', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('dev_interface', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('op_interface', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
