"""empty message

Revision ID: 3cd77cb465be
Revises: 447d1743e0de
Create Date: 2016-02-16 17:23:57.468636

"""

# revision identifiers, used by Alembic.
revision = '3cd77cb465be'
down_revision = '447d1743e0de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'manufacturers',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'manufacturers',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###
