"""empty message

Revision ID: 3f20a8a72d0a
Revises: e8ed4b55f520
Create Date: 2016-01-28 10:12:14.554453

"""

# revision identifiers, used by Alembic.
revision = '3f20a8a72d0a'
down_revision = 'e8ed4b55f520'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'uuid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('uuid', mysql.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
