"""empty message

Revision ID: 7de1ffb7774f
Revises: dd85fa7bd6cf
Create Date: 2016-01-21 14:11:29.733711

"""

# revision identifiers, used by Alembic.
revision = '7de1ffb7774f'
down_revision = 'dd85fa7bd6cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('mac', sa.String(length=20), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('swithc_port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipinfo_server_id'), 'ipinfo', ['server_id'], unique=False)
    op.create_index(op.f('ix_ipinfo_switch_id'), 'ipinfo', ['switch_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipinfo_switch_id'), table_name='ipinfo')
    op.drop_index(op.f('ix_ipinfo_server_id'), table_name='ipinfo')
    op.drop_table('ipinfo')
    ### end Alembic commands ###
