"""empty message

Revision ID: 968c5bad1e86
Revises: a290aa576ceb
Create Date: 2016-01-23 10:54:37.441837

"""

# revision identifiers, used by Alembic.
revision = '968c5bad1e86'
down_revision = 'a290aa576ceb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('os', sa.String(length=20), nullable=True))
    op.drop_column('server', 'os_version')
    op.drop_column('server', 'os_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('os_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('server', sa.Column('os_version', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('server', 'os')
    ### end Alembic commands ###
