"""empty message

Revision ID: a290aa576ceb
Revises: a7642d8ec071
Create Date: 2016-01-22 15:24:30.827576

"""

# revision identifiers, used by Alembic.
revision = 'a290aa576ceb'
down_revision = 'a7642d8ec071'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'vm_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'vm_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
