"""empty message

Revision ID: d62dd02d6e94
Revises: 3cd77cb465be
Create Date: 2016-02-28 17:13:41.273673

"""

# revision identifiers, used by Alembic.
revision = 'd62dd02d6e94'
down_revision = '3cd77cb465be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zbhost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmdb_hostid', sa.Integer(), nullable=True),
    sa.Column('hostid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zbhost_cmdb_hostid'), 'zbhost', ['cmdb_hostid'], unique=True)
    op.create_index(op.f('ix_zbhost_hostid'), 'zbhost', ['hostid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zbhost_hostid'), table_name='zbhost')
    op.drop_index(op.f('ix_zbhost_cmdb_hostid'), table_name='zbhost')
    op.drop_table('zbhost')
    ### end Alembic commands ###
