"""empty message

Revision ID: dd85fa7bd6cf
Revises: 2294cb4ebe5f
Create Date: 2016-01-21 14:10:38.836469

"""

# revision identifiers, used by Alembic.
revision = 'dd85fa7bd6cf'
down_revision = '2294cb4ebe5f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipinfo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('mac', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('device', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('switch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('swithc_port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
