"""empty message

Revision ID: e8ed4b55f520
Revises: 05994d747975
Create Date: 2016-01-25 11:27:34.165423

"""

# revision identifiers, used by Alembic.
revision = 'e8ed4b55f520'
down_revision = '05994d747975'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'hostname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('server', 'idc_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('server', 'inner_ip',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('server', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('server', 'supplier',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'supplier',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('server', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('server', 'inner_ip',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('server', 'idc_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('server', 'hostname',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    ### end Alembic commands ###
