"""empty message

Revision ID: fb6e7286d572
Revises: 34b85bb91295
Create Date: 2016-01-21 15:02:38.821226

"""

# revision identifiers, used by Alembic.
revision = 'fb6e7286d572'
down_revision = '34b85bb91295'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('monitor_mail_group', sa.String(length=32), nullable=True))
    op.drop_column('server', 'monitor_mail_gro')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('monitor_mail_gro', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('server', 'monitor_mail_group')
    ### end Alembic commands ###
